services:
  mongo:
    image: mongo:latest
    container_name: accident_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ai_core:
    build:
      context: .
      dockerfile: Dockerfile.combined
    container_name: accident_ai_core
    restart: unless-stopped
    ports:
      - "5556:5556" # ZMQ Access
      - "5001:5001" # MJPEG Stream
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./accident_crops:/app/accident_crops
      - ./videos:/app/videos
      - ./cctv_eg.mp4:/app/cctv_eg.mp4
      - ./temp_uploads:/app/temp_uploads
    depends_on:
      - mongo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    develop:
      watch:
        - action: sync
          path: ./detector
          target: /app/detector
        - action: sync
          path: ./classifier
          target: /app/classifier
        - action: sync
          path: ./services
          target: /app/services
        - action: sync
          path: ./utils
          target: /app/utils
        - action: sync
          path: ./detector_publisher.py
          target: /app/detector_publisher.py
        - action: sync
          path: ./classifier_subscriber.py
          target: /app/classifier_subscriber.py
        - action: rebuild
          path: ./requirements.combined.txt

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: accident_api
    command: uvicorn services.api_server:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      # Hostname must match service name 'ai_core'
      - DETECTOR_STREAM_URL=http://ai_core:5001/stream.mjpg
      - DETECTOR_HEALTH_URL=http://ai_core:5001/stream.mjpg
    volumes:
      - ./accident_crops:/app/accident_crops
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
      - ai_core
    develop:
      watch:
        - action: sync
          path: ./services
          target: /app/services
        - action: sync
          path: ./utils
          target: /app/utils
        - action: rebuild
          path: ./requirements.api.txt

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: accident_dashboard
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    volumes:
      - ./dashboard:/app
      - /app/node_modules

  prometheus:
    image: prom/prometheus
    container_name: accident_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  mongo_data:


networks:
  default:
    name: accident_net
